$(document).ready(function() {
  $("#formOne").submit(function(event) {
    // const time1Input = $("input#time1").val();
    // const furniture1Input = $("input#furniture1").val();
    // const exclamationInput = $("input#exclamation").val();
    // const negativeExclamationInput = $("input#negativeExclamation").val();
    // const beverage1Input = $("input#beverage1").val();
    // const pluralNoun1Input = $("input#pluralNoun1").val();
    // const room1Input = $("input#room1").val();
    // const adjective1Input = $("input#adjective1").val();
    // const adjective2Input = $("input#adjective2").val();
    // const adjective3Input = $("input#adjective3").val();
    // const food1Input = $("input#food1").val();
    // const emotionAdjective1Input = $("input#emotionAdjective1").val();
    // const adjective4Input = $("input#adjective4").val();
    // const websiteInput = $("input#website").val();
    // const adjective5Input = $("input#adjective5").val();
    // const amountOfTimeInput = $("input#amountOfTime").val();
    // const placeInput = $("input#place").val();
    // const clothing1Input = $("input#clothing1").val();
    // const clothing2Input = $("input#clothing2").val();
    // const bodyPart1Input = $("input#bodyPart1").val();
    // const bodyPart2Input = $("input#bodyPart2").val();
    // const adjective6Input = $("input#adjective6").val();
    // const time2Input = $("input#time2").val();
    // const adjective7Input = $("input#adjective7").val();
    // const adjective8Input = $("input#adjective8").val();
    // const adjective9Input = $("input#adjective9").val();
    // const adverb1Input = $("input#adverb1").val();
    // const adjective10Input = $("input#adjective10").val();
    // const adjective11Input = $("input#adjective11").val();
    // const adjective12Input = $("input#adjective12").val();
    // const adjective13Input = $("input#adjective13").val();
    // const adjective14Input = $("input#adjective14").val();
    // const emotionNounInput = $("input#emotionNoun").val();
    // const noun1Input = $("input#noun1").val();
    // const noun2Input = $("input#noun2").val();
    // const pastVerbInput = $("input#pastVerb").val();
    // const pluralNoun2Input = $("input#pluralNoun2").val();
    // const beverage2Input = $("input#beverage2").val();
    // const tvInput = $("input#tv").val();
    // const numberInput = $("input#number").val();
    // const soundInput = $("input#sound").val();
    // const adjective15Input = $("input#adjective15").val();
    // const verb1Input = $("input#verb1").val();
    // const timeUnitInput = $("input#timeUnit").val();
    // const erAdjectiveInput = $("input#erAdjective").val();
    // const adverb2Input = $("input#adverb2").val();
    // const furniture2Input = $("input#furniture2").val();
    // const pluralNoun3Input = $("input#pluralNoun3").val();
    // const adjective16Input = $("input#adjective16").val();
    // const pluralNoun4Input = $("input#pluralNoun4").val();
    // const negativeAdjectiveInput = $("input#negativeAdjective").val();
    // const adjective17Input = $("input#adjective17").val();

    let momlibArray = ["time1", "furniture1", "exclamation", "negativeExclamation", "beverage1", "pluralNoun1", "room1", "adjective1", "adjective2", "adjective3", "food1", "emotionAdjective1", "adjective4", "website", "adjective5", "amountOfTime", "place", "clothing1", "clothing2", "bodyPart1", "bodyPart2", "adjective6", "time2", "adjective7", "adjective8", "adjective9", "adverb1", "adjective10", "adjective11", "adjective12", "adjective13", "adjective14", "emotionNoun", "noun1", "noun2", "pastVerb", "pluralNoun2", "beverage2", "tv", "number", "sound", "adjective15", "verb1", "timeUnit", "erAdjective", "adverb2", "furniture2", "pluralNoun3", "adjective16", "pluralNoun4", "negativeAdjective", "adjective17"]

    momlibArray.forEach(function(element) {
      let input = $("input#" + element).val();
      $("span." + element).text(input);
    });

    // $(".time1").text(time1Input);
    // $(".furniture1").text(furniture1Input);
    // $(".exclamation").text(exclamationInput);
    // $(".negativeExclamation").text(negativeExclamationInput);
    // $(".beverage1").text(beverage1Input);
    // $(".pluralNoun1").text(pluralNoun1Input);
    // $(".room1").text(room1Input);
    // $(".adjective1").text(adjective1Input);
    // $(".adjective2").text(adjective2Input);
    // $(".adjective3").text(adjective3Input);
    // $(".food1").text(food1Input);
    // $(".emotionAdjective1").text(emotionAdjective1Input);
    // $(".adjective4").text(adjective4Input);
    // $(".website").text(websiteInput);
    // $(".adjective5").text(adjective5Input);
    // $(".amountOfTime").text(amountOfTimeInput);
    // $(".place").text(placeInput);
    // $(".clothing1").text(clothing1Input);
    // $(".clothing2").text(clothing2Input);
    // $(".bodyPart1").text(bodyPart1Input);
    // $(".bodyPart2").text(bodyPart2Input);
    // $(".adjective6").text(adjective6Input);
    // $(".time2").text(time2Input);
    // $(".adjective7").text(adjective7Input);
    // $(".adjective8").text(adjective8Input);
    // $(".adjective9").text(adjective9Input);
    // $(".adverb1").text(adverb1Input);
    // $(".adjective10").text(adjective10Input);
    // $(".adjective11").text(adjective11Input);
    // $(".adjective12").text(adjective12Input);
    // $(".adjective13").text(adjective13Input);
    // $(".adjective14").text(adjective14Input);
    // $(".emotionNoun").text(emotionNounInput);
    // $(".noun1").text(noun1Input);
    // $(".noun2").text(noun2Input);
    // $(".pastVerb").text(pastVerbInput);
    // $(".pluralNoun2").text(pluralNoun2Input);
    // $(".beverage2").text(beverage2Input);
    // $(".tv").text(tvInput);
    // $(".number").text(numberInput);
    // $(".sound").text(soundInput);
    // $(".adjective15").text(adjective15Input);
    // $(".verb1").text(verb1Input);
    // $(".timeUnit").text(timeUnitInput);
    // $(".erAdjective").text(erAdjectiveInput);
    // $(".adverb2").text(adverb2Input);
    // $(".furniture2").text(furniture2Input);
    // $(".pluralNoun3").text(pluralNoun3Input);
    // $(".adjective16").text(adjective16Input);
    // $(".pluralNoun4").text(pluralNoun4Input);
    // $(".negativeAdjective").text(negativeAdjectiveInput);
    // $(".adjective17").text(adjective17Input);

    $("#story").show();

    event.preventDefault();
  });
});